---
- src: https://github.com/artis3n/ansible-role-tailscale.git
- src: https://github.com/nickhammond/ansible-logrotate.git
- src: https://github.com/PyratLabs/ansible-role-k3s
  name: k3s
  scm: git
  version: main
- src: https://github.com/tigattack/ansible-role-mergerfs.git
